matrix:
    include:
        - os: linux
          language: python
          sudo: required
          services: docker
          script: docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build 
        - os: linux
          language: python
          before_install:
            - sudo apt-get update -qq
            - sudo apt-get install -qq numpy scipy
          env: TOXENV=py27,py33,py34
          install: pip install tox
          script: tox
        - os: osx
          language: python
          sudo: required
          before_install: 
            - brew update
            - brew install python numpy scipy
          install: pip install tox
          env: TOXENV=py27
          script: tox
